import Head from "next/head";
// import Image from "next/image";
import HomeMain from "../components/Home/HomeMain";
// import styles from "../styles/Home.module.css";

// export default function Home({ mode, setMode }) {
export default function Home() {
  return (
    <div>
      <Head>
        <title>Next MUI Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <HomeMain setMode={setMode} mode={mode} /> */}
        <HomeMain />
      </main>
    </div>
  );
}
